// WARNING: This file is regenerated by the `cargo func new` command.

mod hello;
mod link_ingester;

// Export the Azure Functions here.
azure_functions::export! {
    hello::hello,
    link_ingester::link_ingester,
}
